const productData = [
    {
        title: "Cotton Casual T-Shirt",
        desc: "Comfortable and breathable casual t-shirt made from high-quality cotton.",
        img: "https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8dHNoaXJ0JTIwbWVufGVufDB8MHwwfHx8MA%3D%3D",
        categories: ["Casual Wear", "T-Shirts"],
        size: ["S", "M", "L"],
        color: ["White", "Black", "Blue"],
        price: 19.99,
        inStock: true,
        createdAt: "2024-01-20T12:00:00.000Z",
        updatedAt: "2024-01-20T12:05:00.000Z"
    },
    {
        title: "Slim Fit Denim Jeans",
        desc: "Stylish and slim-fit denim jeans for a trendy look.",
        img: "https://images.unsplash.com/photo-1560243563-062bfc001d68?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fGglMjZtJTIwamVhbnN8ZW58MHwwfDB8fHww",
        categories: ["Denim", "Jeans"],
        size: ["28", "30", "32", "34"],
        color: ["Blue", "Black"],
        price: 49.99,
        inStock: true,
        createdAt: "2024-01-20T12:10:00.000Z",
        updatedAt: "2024-01-20T12:15:00.000Z"
    },
    {
        title: "Classic Leather Jacket",
        desc: "Timeless leather jacket with a classic design for a rugged yet sophisticated look.",
        img: "https://images.unsplash.com/photo-1489286696299-aa7486820bd5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGVhdGhlciUyMGphY2tldHxlbnwwfDB8MHx8fDA%3D",
        categories: ["Outerwear", "Jackets"],
        size: ["M", "L", "XL"],
        color: ["Brown", "Black"],
        price: 89.99,
        inStock: true,
        createdAt: "2024-01-20T12:20:00.000Z",
        updatedAt: "2024-01-20T12:25:00.000Z"
    },
    {
        title: "Sporty Running Shoes",
        desc: "Lightweight and comfortable running shoes for an active lifestyle.",
        img: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3BvcnQlMjBzaG9lc3xlbnwwfDB8MHx8fDA%3D",
        categories: ["Athletic Shoes", "Running Shoes"],
        size: ["7", "8", "9", "10"],
        color: ["Red", "Black"],
        price: 59.99,
        inStock: true,
        createdAt: "2024-01-20T12:30:00.000Z",
        updatedAt: "2024-01-20T12:35:00.000Z"
    },
    {
        title: "Formal Slim-Fit Suit",
        desc: "Elegant and modern slim-fit suit for formal occasions.",
        img: "https://images.unsplash.com/photo-1515736076039-a3ca66043b27?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2xpbSUyMGZpdCUyMHN1aXR8ZW58MHwwfDB8fHww",
        categories: ["Formal Wear", "Suits"],
        size: ["40R", "42R", "44R"],
        color: ["Navy", "Charcoal"],
        price: 129.99,
        inStock: true,
        createdAt: "2024-01-20T12:40:00.000Z",
        updatedAt: "2024-01-20T12:45:00.000Z"
    },
    {
        title: "Cozy Knit Sweater",
        desc: "Warm and cozy knit sweater for chilly weather.",
        img: "https://images.unsplash.com/photo-1612207956624-0091b244181c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGtuaXQlMjBzd2VhdGVyfGVufDB8MHwwfHx8MA%3D%3D",
        categories: ["Winter Wear", "Sweaters"],
        size: ["S", "M", "L"],
        color: ["Gray", "Burgundy"],
        price: 39.99,
        inStock: true,
        createdAt: "2024-01-20T12:50:00.000Z",
        updatedAt: "2024-01-20T12:55:00.000Z"
    },
    {
        title: "Casual Linen Shorts",
        desc: "Breathable and comfortable linen shorts for a relaxed look.",
        img: "https://images.unsplash.com/photo-1505515512423-7f370c79c5ef?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWVuJTIwc2hvcnRzfGVufDB8MHwwfHx8MA%3D%3D",
        categories: ["Casual Wear", "Shorts"],
        size: ["30", "32", "34"],
        color: ["Khaki", "Navy"],
        price: 29.99,
        inStock: true,
        createdAt: "2024-01-20T13:00:00.000Z",
        updatedAt: "2024-01-20T13:05:00.000Z"
    },
    {
        title: "Vintage Floral Dress",
        desc: "Charming vintage floral dress for a feminine and stylish look.",
        img: "https://images.unsplash.com/photo-1499939667766-4afceb292d05?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZmxvcmFsJTIwZHJlc3N8ZW58MHwwfDB8fHww",
        categories: ["Dresses", "Vintage"],
        size: ["XS", "S", "M"],
        color: ["Floral Pattern"],
        price: 69.99,
        inStock: true,
        createdAt: "2024-01-20T13:10:00.000Z",
        updatedAt: "2024-01-20T13:15:00.000Z"
    },
    {
        "title": "Classic Denim Jacket",
        "desc": "Timeless denim jacket for men",
        "img": "mens_denim_jacket.jpg",
        "categories": ["Jackets", "Men's Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Blue"],
        "price": 49.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:00:00Z", "updatedAt": "2024-01-20T12:00:00Z" }
    },
    {
        "title": "Elegant Blouse",
        "desc": "Sophisticated blouse for women",
        "img": "womens_elegant_blouse.jpg",
        "categories": ["Tops", "Women's Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["White", "Black"],
        "price": 34.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:05:00Z", "updatedAt": "2024-01-20T12:05:00Z" }
    },
    {
        "title": "Graphic T-Shirt",
        "desc": "Fun graphic t-shirt for boys",
        "img": "boys_graphic_tshirt.jpg",
        "categories": ["T-Shirts", "Boys' Apparel"],
        "size": ["4-6", "8-10", "12-14"],
        "color": ["Red", "Blue"],
        "price": 14.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:10:00Z", "updatedAt": "2024-01-20T12:10:00Z" }
    },
    {
        "title": "Floral Sundress",
        "desc": "Adorable floral sundress for girls",
        "img": "girls_floral_sundress.jpg",
        "categories": ["Dresses", "Girls' Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Pink", "Yellow"],
        "price": 29.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:15:00Z", "updatedAt": "2024-01-20T12:15:00Z" }
    },
    {
        "title": "Sporty Joggers",
        "desc": "Comfortable joggers for an active lifestyle",
        "img": "mens_sporty_joggers.jpg",
        "categories": ["Athletic Wear", "Men's Bottoms"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Black", "Gray"],
        "price": 39.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:20:00Z", "updatedAt": "2024-01-20T12:20:00Z" }
    },
    {
        "title": "Casual Sneakers",
        "desc": "Stylish and comfortable sneakers for women",
        "img": "womens_casual_sneakers.jpg",
        "categories": ["Footwear", "Women's Shoes"],
        "size": ["6", "7", "8", "9"],
        "color": ["White", "Rose Gold"],
        "price": 59.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:25:00Z", "updatedAt": "2024-01-20T12:25:00Z" }
    },
    {
        "title": "Hooded Sweatshirt",
        "desc": "Cozy hooded sweatshirt for boys",
        "img": "boys_hooded_sweatshirt.jpg",
        "categories": ["Sweatshirts", "Boys' Apparel"],
        "size": ["4-6", "8-10", "12-14"],
        "color": ["Blue", "Green"],
        "price": 24.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:30:00Z", "updatedAt": "2024-01-20T12:30:00Z" }
    },
    {
        "title": "Denim Skirt",
        "desc": "Trendy denim skirt for girls",
        "img": "girls_denim_skirt.jpg",
        "categories": ["Skirts", "Girls' Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Denim Blue"],
        "price": 19.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:35:00Z", "updatedAt": "2024-01-20T12:35:00Z" }
    },
    {
        "title": "Formal Suit",
        "desc": "Classic formal suit for men",
        "img": "mens_formal_suit.jpg",
        "categories": ["Suits", "Men's Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Black", "Navy"],
        "price": 99.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:40:00Z", "updatedAt": "2024-01-20T12:40:00Z" }
    },
    {
        "title": "Winter Coat",
        "desc": "Warm winter coat for women",
        "img": "womens_winter_coat.jpg",
        "categories": ["Outerwear", "Women's Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Red", "Brown"],
        "price": 79.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:45:00Z", "updatedAt": "2024-01-20T12:45:00Z" }
    },
    {
        "title": "Camouflage Pants",
        "desc": "Cool camouflage pants for boys",
        "img": "boys_camouflage_pants.jpg",
        "categories": ["Pants", "Boys' Apparel"],
        "size": ["4-6", "8-10", "12-14"],
        "color": ["Green", "Brown"],
        "price": 29.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:50:00Z", "updatedAt": "2024-01-20T12:50:00Z" }
    },
    {
        "title": "Ruffled Blouse",
        "desc": "Charming ruffled blouse for girls",
        "img": "girls_ruffled_blouse.jpg",
        "categories": ["Tops", "Girls' Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Pink", "White"],
        "price": 34.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T12:55:00Z", "updatedAt": "2024-01-20T12:55:00Z" }
    },
    {
        "title": "Graphic Tee",
        "desc": "Casual graphic t-shirt for men",
        "img": "mens_graphic_tee.jpg",
        "categories": ["T-Shirts", "Men's Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Gray", "Black"],
        "price": 17.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T13:00:00Z", "updatedAt": "2024-01-20T13:00:00Z" }
    },
    {
        "title": "High-Waisted Jeans",
        "desc": "Trendy high-waisted jeans for women",
        "img": "womens_high_waisted_jeans.jpg",
        "categories": ["Jeans", "Women's Bottoms"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Blue", "Black"],
        "price": 44.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T13:05:00Z", "updatedAt": "2024-01-20T13:05:00Z" }
    },
    {
        "title": "Varsity Jacket",
        "desc": "Sporty varsity jacket for boys",
        "img": "boys_varsity_jacket.jpg",
        "categories": ["Jackets", "Boys' Apparel"],
        "size": ["4-6", "8-10", "12-14"],
        "color": ["Navy", "Red"],
        "price": 39.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T13:10:00Z", "updatedAt": "2024-01-20T13:10:00Z" }
    },
    {
        "title": "Sequin Dress",
        "desc": "Sparkly sequin dress for girls",
        "img": "girls_sequin_dress.jpg",
        "categories": ["Dresses", "Girls' Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Silver", "Pink"],
        "price": 49.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-20T13:15:00Z", "updatedAt": "2024-01-20T13:15:00Z" }
    },
    {
        "title": "Casual Hooded Jacket",
        "desc": "Versatile hooded jacket for all occasions",
        "img": "casual_hooded_jacket.jpg",
        "categories": ["Jackets", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Navy", "Gray"],
        "price": 69.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:00:00Z", "updatedAt": "2024-01-22T12:00:00Z" }
    },
    {
        "title": "Striped Linen Shirt",
        "desc": "Cool and breathable striped linen shirt",
        "img": "striped_linen_shirt.jpg",
        "categories": ["Shirts", "Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Blue", "White"],
        "price": 49.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:05:00Z", "updatedAt": "2024-01-22T12:05:00Z" }
    },
    {
        "title": "Active Jogging Pants",
        "desc": "Comfortable and stretchy jogging pants for workouts",
        "img": "active_jogging_pants.jpg",
        "categories": ["Athletic Wear", "Activewear"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Black", "Green"],
        "price": 29.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:10:00Z", "updatedAt": "2024-01-22T12:10:00Z" }
    },
    {
        "title": "Ruffle Sleeve Blouse",
        "desc": "Chic ruffle sleeve blouse for a trendy look",
        "img": "ruffle_sleeve_blouse.jpg",
        "categories": ["Blouses", "Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Pink", "White"],
        "price": 34.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:15:00Z", "updatedAt": "2024-01-22T12:15:00Z" }
    },
    {
        "title": "Slim Fit Chinos",
        "desc": "Tailored slim fit chinos for a polished look",
        "img": "slim_fit_chinos.jpg",
        "categories": ["Pants", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Khaki", "Navy"],
        "price": 54.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:20:00Z", "updatedAt": "2024-01-22T12:20:00Z" }
    },
    {
        "title": "Suede Ankle Boots",
        "desc": "Stylish suede ankle boots for a fashionable touch",
        "img": "suede_ankle_boots.jpg",
        "categories": ["Footwear", "Shoes"],
        "size": ["6", "7", "8", "9"],
        "color": ["Taupe", "Black"],
        "price": 79.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:25:00Z", "updatedAt": "2024-01-22T12:25:00Z" }
    },
    {
        "title": "Camo Print Hoodie",
        "desc": "Casual camo print hoodie for a laid-back style",
        "img": "camo_print_hoodie.jpg",
        "categories": ["Sweatshirts", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Camouflage"],
        "price": 44.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:30:00Z", "updatedAt": "2024-01-22T12:30:00Z" }
    },
    {
        "title": "Floral Print Jumpsuit",
        "desc": "Vibrant floral print jumpsuit for a playful look",
        "img": "floral_print_jumpsuit.jpg",
        "categories": ["Jumpsuits", "Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Red", "Yellow"],
        "price": 39.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:35:00Z", "updatedAt": "2024-01-22T12:35:00Z" }
    },
    {
        "title": "Casual Sneakers",
        "desc": "Stylish and comfortable sneakers for everyday wear",
        "img": "casual_sneakers.jpg",
        "categories": ["Footwear", "Shoes"],
        "size": ["6", "7", "8", "9"],
        "color": ["White", "Gray"],
        "price": 59.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:40:00Z", "updatedAt": "2024-01-22T12:40:00Z" }
    },
    {
        "title": "Knit Pullover Sweater",
        "desc": "Warm and cozy knit pullover sweater for chilly days",
        "img": "knit_pullover_sweater.jpg",
        "categories": ["Sweaters", "Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Burgundy", "Beige"],
        "price": 49.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:45:00Z", "updatedAt": "2024-01-22T12:45:00Z" }
    },
    {
        "title": "Cargo Jogger Pants",
        "desc": "Functional cargo jogger pants for a trendy look",
        "img": "cargo_jogger_pants.jpg",
        "categories": ["Athletic Wear", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Olive", "Brown"],
        "price": 34.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:50:00Z", "updatedAt": "2024-01-22T12:50:00Z" }
    },
    {
        "title": "Ruffled Blouse",
        "desc": "Charming ruffled blouse for a feminine touch",
        "img": "ruffled_blouse.jpg",
        "categories": ["Blouses", "Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Lavender", "White"],
        "price": 29.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T12:55:00Z", "updatedAt": "2024-01-22T12:55:00Z" }
    },
    {
        "title": "Graphic Tee",
        "desc": "Casual graphic t-shirt for a laid-back style",
        "img": "graphic_tee.jpg",
        "categories": ["T-Shirts", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Gray", "Black"],
        "price": 24.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:00:00Z", "updatedAt": "2024-01-22T13:00:00Z" }
    },
    {
        "title": "High-Waisted Jeans",
        "desc": "Trendy high-waisted jeans for a stylish look",
        "img": "high_waisted_jeans.jpg",
        "categories": ["Jeans", "Bottoms"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Blue", "Black"],
        "price": 64.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:05:00Z", "updatedAt": "2024-01-22T13:05:00Z" }
    },
    {
        "title": "Varsity Jacket",
        "desc": "Sporty varsity jacket for a cool and casual look",
        "img": "varsity_jacket.jpg",
        "categories": ["Jackets", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Navy", "Red"],
        "price": 54.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:10:00Z", "updatedAt": "2024-01-22T13:10:00Z" }
    },
    {
        "title": "Sequin Dress",
        "desc": "Sparkly sequin dress for a glamorous night out",
        "img": "sequin_dress.jpg",
        "categories": ["Dresses", "Fashion"],
        "size": ["6-8", "10-12", "14-16"],
        "color": ["Silver", "Gold"],
        "price": 89.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:15:00Z", "updatedAt": "2024-01-22T13:15:00Z" }
    },
    {
        "title": "Leather Biker Jacket",
        "desc": "Edgy leather biker jacket for a bold style",
        "img": "leather_biker_jacket.jpg",
        "categories": ["Jackets", "Fashion"],
        "size": ["S", "M", "L", "XL"],
        "color": ["Black"],
        "price": 99.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:20:00Z", "updatedAt": "2024-01-22T13:20:00Z" }
    },
    {
        "title": "Boho Maxi Dress",
        "desc": "Bohemian-style maxi dress for a free-spirited look",
        "img": "boho_maxi_dress.jpg",
        "categories": ["Dresses", "Fashion"],
        "size": ["XS", "S", "M", "L"],
        "color": ["Floral", "Blue"],
        "price": 74.99,
        "inStock": true,
        "timestamps": { "createdAt": "2024-01-22T13:25:00Z", "updatedAt": "2024-01-22T13:25:00Z" }
    }

];

module.exports = { data: productData };